from snakemake.utils import min_version
##### set minimum snakemake version #####
min_version("7.32.3")

##### setup report #####
configfile: "../config/config.yaml"

##### load rules #####
include: "rules/trim.smk"

rule all:
    input:
        "../results/trimal.fasta"
